name: Man10DeliveryService
version: @version@
main: ltotj.minecraft.man10deliveryservice.Main
api-version: 1.21
depend: [Vault]
commands:
  mdrec:
    usage: ""
  mdsend:
    usuage: "§d/mdsend <送りたい人> (ボックスの名前)"
  mdlog:
    usuage: ""
  mletter:
    usuage: ""
  mdop:
    usuage: ""

permissions:
  mdelivery.admin:
      default: op
      children:
        mdelivery.player: true
  mdelivery.player:
      default: op